# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WebcamStreamer.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'WebcamStreamer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14WebcamStreamer.proto\"R\n\tFrameData\x12\x11\n\tcamera_id\x18\x01 \x01(\x05\x12\r\n\x05\x66rame\x18\x02 \x01(\x0c\x12\x0f\n\x07toe_deg\x18\x03 \x01(\x02\x12\x12\n\ncamber_deg\x18\x04 \x01(\x02\"\x1b\n\x08\x46rameAck\x12\x0f\n\x07message\x18\x01 \x01(\t26\n\rFrameReceiver\x12%\n\nSendFrames\x12\n.FrameData\x1a\t.FrameAck(\x01\x42\x16\xaa\x02\x13WebcamStreamer.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WebcamStreamer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\023WebcamStreamer.Grpc'
  _globals['_FRAMEDATA']._serialized_start=24
  _globals['_FRAMEDATA']._serialized_end=106
  _globals['_FRAMEACK']._serialized_start=108
  _globals['_FRAMEACK']._serialized_end=135
  _globals['_FRAMERECEIVER']._serialized_start=137
  _globals['_FRAMERECEIVER']._serialized_end=191
# @@protoc_insertion_point(module_scope)
