# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WebcamStreamer.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'WebcamStreamer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14WebcamStreamer.proto\x12\x06webcam\")\n\x05\x46rame\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"0\n\rFrameResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2I\n\x0eWebcamStreamer\x12\x37\n\x0bStreamVideo\x12\r.webcam.Frame\x1a\x15.webcam.FrameResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WebcamStreamer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAME']._serialized_start=32
  _globals['_FRAME']._serialized_end=73
  _globals['_FRAMERESPONSE']._serialized_start=75
  _globals['_FRAMERESPONSE']._serialized_end=123
  _globals['_WEBCAMSTREAMER']._serialized_start=125
  _globals['_WEBCAMSTREAMER']._serialized_end=198
# @@protoc_insertion_point(module_scope)
